import { Inter } from "next/font/google";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WanderMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        <div className="border bg-gray-20 w-[90vw] mx-auto my-4" />
        <p className="regular-14 w-full text-center text-gray-30">
          2024 All rights reserved
        </p>
      </body>
    </html>
  );
}
